### PR TITLE
Discriminate home layout tags

### PR DESCRIPTION
**Pull request by johangiraud**

### CODE REVIEW

**Comment by johangiraud** [comment]
I don't understand why tests `test_draft_image_should_save_and_render` and `test_profile_image_should_save_and_render` broke. Can you help me with that guys? @davidbgk @vinyll

**Comment by johangiraud** [comment]
> I don't understand why tests test_draft_image_should_save_and_render and test_profile_image_should_save_and_render broke. Can you help me with that guys? @davidbgk @vinyll

Hum très étrange, while checking tests with `pytest` via iTerm, these didn't pass. And now with travis, they do.
Good then !

**Comment by vinyll** [comment]
@cafebabel-webmaster you may be missing the folders where the pictures should be saved.
you may want to run the following command from your cafebabel project root dir: `make make-dirs`

**Comment by johangiraud** [comment]
> @cafebabel-webmaster you may be missing the folders where the pictures should be saved.
you may want to run the following command from your cafebabel project root dir: make make-dirs

Done. Thanks

**Pull request merged**
