### PR TITLE
changer la forme pour la non visibilité des traductions en cours

### LINKED ISSUE #458: Rendre privé les drafts traductions
Exemple : https://cafebabel.com/fr/article/catastrophe-une-nuit-dans-le-bouleversement-de-la-jeunesse-francaise-5ae00c07f723b35a145e82e5/ 
Sur cette page, seule la pastille "IT" est verte, les autres ne sont pas cliquables. ok.

**Mais!**
En pied de page, on trouve 👍 
*Review this article in: es: [spa] Catastrophe o la metamorfosis de la juventud francesa*
Qui pointe sur : https://cafebabel.com/es/article/translation/5ae00c08f723b35a145e82f0/

3 Questions : 
- pourquoi le bouton "ES" n'est pas actif en haut de la page ?
- Pourquoi l'URL contient un /translate/ alors que la version italienne n'en contient pas ?
- pourquoi la fin de cette URL n'est pas réécrite ?

### PR DESCRIPTION
**Pull request by johangiraud**
fix #458

### CODE REVIEW

**Comment by johangiraud** [comment]
I'd like to make the button visible for editors (already running 😉) + for the current translator. For instance, if I'm not an editor, I start translating an article and I submit it. If I visit the VO page, I want to see the button like that:
capture d ecran 2018-05-14 a 15 35 04
How can I discriminate this user: the translator of the article?
@vinyll @davidbgk 

Maybe somethin like `translator.is_me()`?

**Comment by johangiraud** [comment]
@vinyll Also need your help here (see comment above)

**Comment by johangiraud** [comment]
@vinyll is it linked to https://github.com/cafebabel/cafebabel.com/issues/458 ?

**Comment by vinyll** [comment]
First of all we would need a `title` on these buttons. I personnally don't know the color codes and I still need to read the URL it will go to to guess if it's a translation that exists, if it's the original article or if it's to be created.

To answer your original question: it's a new little feature to put in place. We would then need something like a helper that would detect if the user is the translator of a certain article in a certain language.

**Comment by johangiraud** [comment]
>First of all we would need a title on these buttons. I personnally don't know the color codes and I still need to read the URL it will go to to guess if it's a translation that exists, if it's the original article or if it's to be created.

Ok ! https://github.com/cafebabel/cafebabel.com/pull/487/commits/277533f5cf1401c6a946f166bac4d2b5442eb604

**Comment by johangiraud** [comment]
>To answer your original question: it's a new little feature to put in place. We would then need something like a helper that would detect if the user is the translator of a certain article in a certain language.

Yep, that's what we have to do. For now it is only visible for editors. But we need it to be visible for the only translator.

**Comment by vinyll** [comment]
Can you make an issue with that and ping @ffameli for prioritizing?

**Comment by johangiraud** [comment]
For François and me, it was already planned like that.

Can you help me fixing the tests? I tried to add `title="Translate this article in fr"` but it didn't work :-(

**Comment by vinyll** [comment]
Can you push your test fix trial to see what is breaking?

**Comment by johangiraud** [comment]
Yep= https://github.com/cafebabel/cafebabel.com/pull/487/commits/3b07ddaa14b81b91c2ba03162b6ee4c1711cf482

**Comment by ffameli** [comment]
Les traductions en cours ne sont visbiles que pour le traducteur qui l'a réservé + l'ensemble des éditeurs. 
Alors pour ces profils seulement une pastille rose doit les prévenir que la traduction est réservée dans la langue concernée. Il ne me semble pas que ce soit une nouvelle fonction, mais une mise en forme de la privatisation des traductions. @vinyll confirmes tu ?

**Comment by johangiraud** [comment]
Hey @vinyll voilà tu sais c'était cette PR, j'avais déjà dit d'afficher le lien vers le draft en cours uniquement pour les éditeurs et je te demandais comment rendre visible le lien aussi pour celui qui a créé la traduction. Comme tu avais répondu et tout je pensais que c'était clair pour toi. ;-) Que proposes-tu ?

**Comment by johangiraud** [comment]
et aussi je n'arrive pas à fixer le test, je peux te demander de l'aide @vinyll

**Comment by johangiraud** [comment]
@vinyll

**Comment by johangiraud** [comment]
Bon je supprime ces tests @vinyll

**Comment by vinyll** [comment]
Plutot que de supprimer ces tests, il vaut mieux désactiver le controle des tests: https://github.com/cafebabel/cafebabel.com/settings/branches/master et autoriser quand un test ne passe pas et que l'application ne répond pas comme attendu.
Ca laissera comprendre pourquoi ca casse le jour où on a des régressions plutôt que d'être en aveugle ;)

**Comment by johangiraud** [comment]
D'accord, merci !

**Pull request closed without merging**
