### PR TITLE
Styles article detail infos

### PR DESCRIPTION
**Pull request by johangiraud**

### CODE REVIEW

**Review by vinyll — COMMENTED** [review]
I feel like I made this review in the other PR.

**Comment by johangiraud** [comment]
You are right, I created the PR `styles-articles-detail-infos` from `participation-button-styles`

**Comment by johangiraud** [comment]
Possible to merge this one guys? @davidbgk @vinyll

**Comment by davidbgk** [comment]
@cafebabel-webmaster is that empty? 🙈

**Comment by johangiraud** [comment]
I created this branch from another one that we have already merged. So I guess changes that were in common with the other one are already merged as well.

**Comment by vinyll** [comment]
Should we close this empty PR?

**Comment by johangiraud** [comment]
We need a reviewer here to be able to merge :-)

**Comment by vinyll** [comment]
PR is empty

**Pull request closed without merging**
