### PR TITLE
network page layout

### LINKED ISSUE #395: Page Network
- Discriminer la page tag network pour pouvoir la styler autrement

### PR DESCRIPTION
**Pull request by johangiraud**
fix #395

### CODE REVIEW

**Comment by johangiraud** [comment]
Hum just a problem on safari 10.1. window size between 750px and 1300px: 
capture d ecran 2018-04-10 a 16 28 22
`articles` are more than 100% wide :-( Any help will be great :-)
This should be this way:
capture d ecran 2018-04-10 a 16 30 47

**Review by vinyll — APPROVED** [review]
You're making css look beautiful ❤️

**Review by davidbgk — APPROVED** [review]
👍

**Comment by johangiraud** [comment]
> You're making css look beautiful ❤️

😀

**Pull request merged**
