### PR TITLE
Do not allow translations from translations, fix #274

### LINKED ISSUE #274: Traduction à partir d'une traduction impossible
ETQ traducteur je ne veux pas pouvoir faire de traduction à partir d'une traduction existante afin de préserver la consistance de l'article

- [x] ne doit afficher que les traductions possibles à partir de la langue racine

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by davidbgk** [comment]
@cafebabel-webmaster I set you as a reviewer mainly to check with editors if it's now pertinent for editors, not sure if that should be @pointbar job but it's probably easier being close to them 😉

**Review by johangiraud — CHANGES_REQUESTED** [review]
If I visit a non-original-language article, I can still create a translation by hitting a select-language button: 
capture d ecran 2018-04-03 a 11 49 10

**Comment by vinyll** [comment]
@cafebabel-webmaster: the translations are based on the original article. See the translation id `…a516` and the original article that the translation will be based on `…a515`

screen shot 2018-04-03 at 12 43 55 pm

**Comment by johangiraud** [comment]
> @cafebabel-webmaster: the translations are based on the original article. See the translation id …a516 and the original article that the translation will be based on …a515

ah ok, looking good to me then!

**Comment by davidbgk** [comment]
> ah ok, looking good to me then!

Can I get a new review then? :)

**Review by vinyll — APPROVED** [review]

**Review by johangiraud — APPROVED** [review]

**Pull request merged**
