### PR TITLE
Profile-edit page layout

### PR DESCRIPTION
**Pull request by johangiraud**

### CODE REVIEW

**Comment by johangiraud** [comment]
`translation` is undefined in _users/edit.html_. How can I define it? @vinyll @davidbgk

**Comment by johangiraud** [comment]
Here I need help to close :

>`translation` is undefined in users/edit.html. How can I define it? @vinyll @davidbgk

**Comment by johangiraud** [comment]
I guess it just needs to be declared somewhere in the `helper.js` or so? @vinyll

**Comment by vinyll** [comment]
@cafebabel-webmaster: I'm not certain I understand your issue well.
`{% macro contribution_list() %}` should probably `{% macro contribution_list(articles, type) %}`
where `type` can be "translations" or "articles" and `articles` can be a list of translations or of articles.

**Comment by johangiraud** [comment]
No, I need it to be both at the same time: article list and translation list. Exactly the way it works in `user/detail` actually @vinyll

**Comment by vinyll** [comment]
The translations and the articles are not mixed in the HTML.
In users/details.html, you can do:
```html
…
{% macro contribution_list(articles, 'articles') %}
…
{% macro contribution_list(translations, 'translations') %}
…
```

**Comment by johangiraud** [comment]
Ok I try

**Comment by johangiraud** [comment]
No, because in `{{ contribution_list(articles, 'articles' }}` I would need `translations` variable too and the other way around.

**Review by vinyll — APPROVED** [review]

**Comment by vinyll** [comment]
You're getting into the next step in Python! 🐍

**Comment by johangiraud** [comment]
>You're getting into the next step in Python! 🐍

Yeah!

**Pull request merged**
